#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -eDP1 I II III IV V VI VII VIII IX X

bspc config border_width        2 
bspc config window_gap          13
bspc config normal_border_color "#342c4c"
bspc config active_border_color "#FEE5A3"
bspc config focused_border_color "#FEE5A3"
bspc config presel_feedback_color "#D6A36A"
bspc config focus_follows_pointer true
bspc config top_padding 20

bspc config split_ratio          0.5
bspc config border_radius         15
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#feh --bg-fill /home/atifu/Downloads/gruvgirl.jpg &

wal -i /home/atifu/Downloads/gruvgirl.jpg &
. "${HOME}/.cache/wal/colors.sh"
picom --config /home/atifu/.config/picom/picom.conf/file &

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
cp -r ~/Public/poly/bsp/polybar ~/.config/ &
~/.config/polybar/launch.sh &
